# Generated by Django 3.1.1 on 2021-06-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField(max_length=10)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
