# Generated by Django 3.1.1 on 2021-06-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0002_auto_20210609_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='id_number',
            field=models.CharField(max_length=10),
        ),
    ]
